name: ASP.NET_CSharp_pipeline

on:
  push:
    branches:
      - main

jobs:
  checkstyle_aspnet:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.200'  

      - name: Restore dependencies
        run: dotnet restore

      - name: Check style
        run: |
          dotnet build --no-restore --no-incremental --configuration Release
        